"""Rasterises meshpunk-logo.svg into src/display/splash_logo.h.

Chrome (headless) renders the SVG on black at the splash size, ImageMagick
dumps the pixels as raw RGB888, and this script packs them as big-endian
RGB565 words: the byte order of LVGL's LV_COLOR_16_SWAP buffers, which the
display backends push unchanged with tft.pushColors(..., swap=false).

Run from the project root with the PlatformIO Python (standard library only):
  C:/Users/noahl/.platformio/penv/Scripts/python.exe make_splash_logo.py
Options: --chrome PATH, --magick PATH, --width N (default 320; the height
follows the SVG's 960x300 aspect), --svg PATH, --out PATH.
"""
import argparse
import os
import subprocess
import sys
import tempfile

DEFAULT_CHROME = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
DEFAULT_MAGICK = r"C:\Program Files\ImageMagick-7.1.2-Q16-HDRI\magick.exe"
SVG_W, SVG_H = 960, 300


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chrome", default=DEFAULT_CHROME)
    ap.add_argument("--magick", default=DEFAULT_MAGICK)
    ap.add_argument("--width", type=int, default=320)
    ap.add_argument("--svg", default="meshpunk-logo.svg")
    ap.add_argument("--out", default=os.path.join("src", "display", "splash_logo.h"))
    args = ap.parse_args()

    width = args.width
    height = round(width * SVG_H / SVG_W)
    svg = os.path.abspath(args.svg)
    if not os.path.isfile(svg):
        sys.exit("make_splash_logo: %s not found" % svg)

    with tempfile.TemporaryDirectory() as tmp:
        html = os.path.join(tmp, "logo.html")
        png = os.path.join(tmp, "logo.png")
        raw = os.path.join(tmp, "logo.rgb")
        with open(html, "w", encoding="utf-8") as f:
            f.write(
                "<!doctype html><html><head><style>"
                "html,body{margin:0;padding:0;background:#000;overflow:hidden}"
                "img{display:block;width:%dpx;height:%dpx}"
                "</style></head><body><img src=\"file:///%s\"></body></html>"
                % (width, height, svg.replace("\\", "/"))
            )
        # A private profile keeps this run separate from a Chrome that is
        # already open; --headless attaches to it otherwise.
        subprocess.check_call([
            args.chrome, "--headless=new", "--disable-gpu", "--hide-scrollbars",
            "--force-device-scale-factor=1", "--no-first-run",
            "--user-data-dir=" + os.path.join(tmp, "profile"),
            "--window-size=%d,%d" % (width, height),
            "--screenshot=" + png,
            "file:///" + html.replace("\\", "/"),
        ])
        subprocess.check_call([args.magick, png, "-depth", "8", "rgb:" + raw])
        with open(raw, "rb") as f:
            data = f.read()

    expected = width * height * 3
    if len(data) != expected:
        sys.exit("make_splash_logo: got %d bytes of RGB, expected %d" % (len(data), expected))

    words = []
    for i in range(0, len(data), 3):
        r, g, b = data[i], data[i + 1], data[i + 2]
        c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        words.append(((c & 0xFF) << 8) | (c >> 8))   # big-endian word

    lines = [
        "// splash_logo.h - generated by make_splash_logo.py from meshpunk-logo.svg;",
        "// do not edit. %dx%d RGB565 as big-endian words (LV_COLOR_16_SWAP order)," % (width, height),
        "// pushed unchanged by display_dev_splash().",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define SPLASH_LOGO_W %d" % width,
        "#define SPLASH_LOGO_H %d" % height,
        "",
        "static const uint16_t kSplashLogo[SPLASH_LOGO_W * SPLASH_LOGO_H] = {",
    ]
    for i in range(0, len(words), 16):
        lines.append("  " + ", ".join("0x%04X" % w for w in words[i:i + 16]) + ",")
    lines.append("};")
    lines.append("")
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("make_splash_logo: wrote %s (%dx%d, %d bytes of pixels)"
          % (args.out, width, height, len(words) * 2))


if __name__ == "__main__":
    main()
